language: cpp

services:
  - docker

before_install:
  - docker pull matgla/esp8266
  - docker ps -a
  - pip install --user cpp-coveralls
script:
  - docker run -v $(pwd):/mnt/repo -it matgla/esp8266 /bin/sh -c "cd /mnt/repo && sh run_tests.sh && sh build_x86.sh"

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - coveralls --exclude lib --exclude test --exclude src/hal --gcov-options '\-lp'
