language: cpp

services:
  - docker

before_install:
  - docker pull matgla/esp8266
  - docker ps -a
  - sudo apt-get install lcov 
  - gem install coveralls-lcov
script:
  - docker run -v $(pwd):/mnt/repo -it matgla/esp8266 /bin/sh -c "cd /mnt/repo && sh run_tests.sh && sh build_x86.sh"

after_success:
  - cd bin_tests
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'test/*' '/usr/*' 'lib/*' 'src/hal*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls
