set(COMMON_SRC_DIR "${PROJECT_SOURCE_DIR}/src")

set(common_srcs
    ${COMMON_SRC_DIR}/dispatcher/handlers.cpp
    ${COMMON_SRC_DIR}/dispatcher/messageHandler.cpp
    ${COMMON_SRC_DIR}/dispatcher/dispatcher.cpp
    ${COMMON_SRC_DIR}/dispatcher/jsonHandler.cpp
    ${COMMON_SRC_DIR}/dispatcher/handler/handshakeHandler.cpp
    ${COMMON_SRC_DIR}/dispatcher/handler/getInfoHandler.cpp
    ${COMMON_SRC_DIR}/settings/settings.cpp
    ${COMMON_SRC_DIR}/logger/logger.cpp
    ${COMMON_SRC_DIR}/logger/loggerBase.cpp
    ${COMMON_SRC_DIR}/logger/loggerConf.cpp
    ${COMMON_SRC_DIR}/logger/socketLogger.cpp
    ${COMMON_SRC_DIR}/logger/stdOutLogger.cpp
    ${COMMON_SRC_DIR}/logger/fileLogger.cpp
    ${COMMON_SRC_DIR}/logger/stdErrLogger.cpp
    ${COMMON_SRC_DIR}/stream/socketBuffer.cpp
    ${COMMON_SRC_DIR}/stream/socketStream.cpp
    ${COMMON_SRC_DIR}/stream/fileBuffer.cpp
    ${COMMON_SRC_DIR}/stream/fileOStream.cpp
    ${COMMON_SRC_DIR}/statemachine/mcuConnection.cpp
    ${COMMON_SRC_DIR}/statemachine/mcuConnectionFrontEnd.cpp
    ${COMMON_SRC_DIR}/timer/intervalTimer.cpp
    ${COMMON_SRC_DIR}/timer/manager.cpp
    ${COMMON_SRC_DIR}/timer/timeoutTimer.cpp
    ${COMMON_SRC_DIR}/protocol/frameHandler.cpp
    ${COMMON_SRC_DIR}/protocol/packetHandler.cpp
)

set(common_incs
    ${COMMON_SRC_DIR}/container/buffer.hpp
    ${COMMON_SRC_DIR}/hal/fs/file.hpp
    ${COMMON_SRC_DIR}/hal/fs/filesystem.hpp
    ${COMMON_SRC_DIR}/hal/net/http/asyncHttpRequest.hpp
    ${COMMON_SRC_DIR}/hal/net/http/asyncHttpServer.hpp
    ${COMMON_SRC_DIR}/hal/net/http/fwd.hpp
    ${COMMON_SRC_DIR}/hal/net/http/httpMethod.hpp
    ${COMMON_SRC_DIR}/hal/net/socket/tcpClient.hpp
    ${COMMON_SRC_DIR}/hal/net/socket/tcpServer.hpp
    ${COMMON_SRC_DIR}/hal/net/socket/websocket.hpp
    ${COMMON_SRC_DIR}/hal/serial/serialPort.hpp
    ${COMMON_SRC_DIR}/hal/time/sleep.hpp
    ${COMMON_SRC_DIR}/hal/time/time.hpp
    ${COMMON_SRC_DIR}/dispatcher/dispatcher.hpp
    ${COMMON_SRC_DIR}/dispatcher/jsonHandler.hpp
    ${COMMON_SRC_DIR}/dispatcher/handlers.hpp
    ${COMMON_SRC_DIR}/dispatcher/IDataReceiver.hpp
    ${COMMON_SRC_DIR}/dispatcher/IFrameHandler.hpp
    ${COMMON_SRC_DIR}/dispatcher/messageHandler.hpp
    ${COMMON_SRC_DIR}/dispatcher/handler/handshakeHandler.hpp
    ${COMMON_SRC_DIR}/dispatcher/handler/getInfoHandler.hpp
    ${COMMON_SRC_DIR}/dispatcher/stmMessageReceiver.hpp
    ${COMMON_SRC_DIR}/logger/ILogger.hpp
    ${COMMON_SRC_DIR}/logger/logger.hpp
    ${COMMON_SRC_DIR}/logger/loggerBase.hpp
    ${COMMON_SRC_DIR}/logger/loggerConf.hpp
    ${COMMON_SRC_DIR}/logger/socketLogger.hpp
    ${COMMON_SRC_DIR}/logger/fileLogger.hpp
    ${COMMON_SRC_DIR}/logger/stdOutLogger.hpp
    ${COMMON_SRC_DIR}/logger/stdErrLogger.hpp
    ${COMMON_SRC_DIR}/message/IMessage.hpp
    ${COMMON_SRC_DIR}/message/messages.hpp
    ${COMMON_SRC_DIR}/statemachine/mcuConnection.hpp
    ${COMMON_SRC_DIR}/statemachine/mcuConnectionFrontEnd.hpp
    ${COMMON_SRC_DIR}/serializer/serializer.hpp
    ${COMMON_SRC_DIR}/settings/settings.hpp
    ${COMMON_SRC_DIR}/stream/socketBuffer.hpp
    ${COMMON_SRC_DIR}/stream/fileBuffer.hpp
    ${COMMON_SRC_DIR}/stream/fileOStream.hpp
    ${COMMON_SRC_DIR}/stream/socketStream.hpp
    ${COMMON_SRC_DIR}/timer/IManager.hpp
    ${COMMON_SRC_DIR}/timer/intervalTimer.hpp
    ${COMMON_SRC_DIR}/timer/ITimer.hpp
    ${COMMON_SRC_DIR}/timer/manager.hpp
    ${COMMON_SRC_DIR}/timer/timeoutTimer.hpp
    ${COMMON_SRC_DIR}/utils/types.hpp
    ${COMMON_SRC_DIR}/protocol/frame.hpp
    ${COMMON_SRC_DIR}/protocol/IFrame.hpp
    ${COMMON_SRC_DIR}/protocol/frameHandler.hpp
    ${COMMON_SRC_DIR}/protocol/packetHandler.hpp
    ${COMMON_SRC_DIR}/protocol/messages/control.hpp
)
